-- ============================================================================
-- Overlap — complete database setup, in one file.
--
-- This is every file in supabase/migrations/ concatenated in order, for people
-- setting up through the Supabase dashboard instead of the CLI:
--
--   Supabase project -> SQL Editor -> New query -> paste all of this -> Run
--
-- Safe to re-run: every statement is written to be idempotent (IF NOT EXISTS,
-- DROP POLICY IF EXISTS, ON CONFLICT DO UPDATE).
--
-- If you're using the Supabase CLI instead, ignore this file and run
-- `supabase db push` — it applies supabase/migrations/* and tracks which have
-- already run. Don't do both; they create the same objects.
--
-- Generated by scripts/build-setup-sql.sh — edit the migrations, not this file.
-- ============================================================================


-- ============================================================================
-- 0001_base_schema.sql
-- ============================================================================

-- Base schema, unchanged from luma-clone's database-setup.sql except for the
-- DROP POLICY IF EXISTS lines, which make `supabase db push` re-runnable.
-- Everything this project adds lives in the later migrations.

-- Create events table
CREATE TABLE IF NOT EXISTS events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  start_date TIMESTAMP WITH TIME ZONE NOT NULL,
  end_date TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT,
  is_public BOOLEAN DEFAULT true,
  is_free BOOLEAN DEFAULT true,
  requires_approval BOOLEAN DEFAULT false,
  capacity INTEGER,
  theme TEXT DEFAULT 'minimal',
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create attendees table
CREATE TABLE IF NOT EXISTS attendees (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id UUID REFERENCES events(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(event_id, user_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendees ENABLE ROW LEVEL SECURITY;

-- Create policies for events table
DROP POLICY IF EXISTS "Users can view public events" ON events;
CREATE POLICY "Users can view public events" ON events
  FOR SELECT USING (is_public = true OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create their own events" ON events;
CREATE POLICY "Users can create their own events" ON events
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own events" ON events;
CREATE POLICY "Users can update their own events" ON events
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own events" ON events;
CREATE POLICY "Users can delete their own events" ON events
  FOR DELETE USING (auth.uid() = user_id);

-- Create policies for attendees table
DROP POLICY IF EXISTS "Users can view event attendees" ON attendees;
CREATE POLICY "Users can view event attendees" ON attendees
  FOR SELECT USING (
    auth.uid() = user_id OR 
    EXISTS (
      SELECT 1 FROM events 
      WHERE events.id = attendees.event_id 
      AND events.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can register for events" ON attendees;
CREATE POLICY "Users can register for events" ON attendees
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own attendance" ON attendees;
CREATE POLICY "Users can update their own attendance" ON attendees
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Event owners can manage attendees" ON attendees;
CREATE POLICY "Event owners can manage attendees" ON attendees
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM events 
      WHERE events.id = attendees.event_id 
      AND events.user_id = auth.uid()
    )
  );

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_events_user_id ON events(user_id);
CREATE INDEX IF NOT EXISTS idx_events_start_date ON events(start_date);
CREATE INDEX IF NOT EXISTS idx_events_public ON events(is_public);
CREATE INDEX IF NOT EXISTS idx_attendees_event_id ON attendees(event_id);
CREATE INDEX IF NOT EXISTS idx_attendees_user_id ON attendees(user_id);

-- ============================================================================
-- 0002_identity_tags.sql
-- ============================================================================

-- Tags, cover image, and the private per-user preferences table.
-- Section 3 of the setup outline.

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS cover_image_url TEXT,
  ADD COLUMN IF NOT EXISTS identity_tags   TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS event_type_tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS vibe_tags       TEXT[] NOT NULL DEFAULT '{}';

-- GIN indexes so tag-filter queries stay fast as the table grows.
CREATE INDEX IF NOT EXISTS idx_events_identity_tags   ON events USING GIN (identity_tags);
CREATE INDEX IF NOT EXISTS idx_events_event_type_tags ON events USING GIN (event_type_tags);
CREATE INDEX IF NOT EXISTS idx_events_vibe_tags       ON events USING GIN (vibe_tags);

-- Private per-user preferences — NEVER exposed publicly. Policies live in 0003.
CREATE TABLE IF NOT EXISTS user_preferences (
  user_id       UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  identity_tags TEXT[] NOT NULL DEFAULT '{}',
  updated_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- The tag vocabulary is enforced in the database as well as in src/utils/tags.js.
-- Without this a hand-rolled REST call could write tags the filter UI will never
-- render, and they would be invisible in the product but present in the data.
CREATE OR REPLACE FUNCTION tags_are_subset(tags TEXT[], allowed TEXT[])
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT tags <@ allowed;
$$;

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_identity_tags_valid;
ALTER TABLE events ADD CONSTRAINT events_identity_tags_valid CHECK (
  tags_are_subset(identity_tags, ARRAY[
    'trans_masc','trans_fem','sapphic','gay','lesbian','bi_pan',
    'nb','cis_women','cis_men','allies','all_welcome'
  ])
);

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_event_type_tags_valid;
ALTER TABLE events ADD CONSTRAINT events_event_type_tags_valid CHECK (
  tags_are_subset(event_type_tags, ARRAY[
    'party','meetup','workshop','sports','art','dating_mixer','support_group'
  ])
);

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_vibe_tags_valid;
ALTER TABLE events ADD CONSTRAINT events_vibe_tags_valid CHECK (
  tags_are_subset(vibe_tags, ARRAY[
    '18+','21+','free','ticketed','accessible_venue','alcohol_free'
  ])
);

ALTER TABLE user_preferences DROP CONSTRAINT IF EXISTS user_preferences_identity_tags_valid;
ALTER TABLE user_preferences ADD CONSTRAINT user_preferences_identity_tags_valid CHECK (
  tags_are_subset(identity_tags, ARRAY[
    'trans_masc','trans_fem','sapphic','gay','lesbian','bi_pan',
    'nb','cis_women','cis_men','allies','all_welcome'
  ])
);

-- Length limits to match the Zod schemas in src/utils/validation.js, so the cap
-- holds even for a caller that never loads the frontend.
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_title_length;
ALTER TABLE events ADD CONSTRAINT events_title_length
  CHECK (char_length(title) BETWEEN 3 AND 120);

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_description_length;
ALTER TABLE events ADD CONSTRAINT events_description_length
  CHECK (description IS NULL OR char_length(description) <= 4000);

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_location_length;
ALTER TABLE events ADD CONSTRAINT events_location_length
  CHECK (location IS NULL OR char_length(location) <= 200);

-- ============================================================================
-- 0003_rls_and_privacy.sql
-- ============================================================================

-- Section 4 of the outline: RLS for the new table, plus two gaps in the
-- inherited policies from 0001.

ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;

-- Preferences: strictly private, no exceptions. There is deliberately no public
-- SELECT policy, so an anonymous or mismatched JWT sees zero rows — not a
-- filtered subset.
DROP POLICY IF EXISTS "users manage own preferences only" ON user_preferences;
CREATE POLICY "users manage own preferences only"
  ON user_preferences FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Two inherited UPDATE policies have a USING clause but no WITH CHECK. USING
-- decides which rows you may update; WITH CHECK decides what they may look like
-- afterwards. Without it, the owner of a row can update it and hand ownership
-- to someone else (events.user_id) or reassign an RSVP to another account
-- (attendees.user_id) — the row passes USING on the way in and is unchecked on
-- the way out.
DROP POLICY IF EXISTS "Users can update their own events" ON events;
CREATE POLICY "Users can update their own events" ON events
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own attendance" ON attendees;
CREATE POLICY "Users can update their own attendance" ON attendees
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Public attendee counts.
-- Attendee rows are private (you see your own; the organiser sees all), so the
-- "N going" number on a public card cannot come from count(*) over attendees.
-- Keep a denormalised counter on events instead, maintained by a definer
-- trigger that may write a column the caller's own policies would refuse.
ALTER TABLE events ADD COLUMN IF NOT EXISTS going_count INTEGER NOT NULL DEFAULT 0;

CREATE OR REPLACE FUNCTION sync_event_going_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target UUID := COALESCE(NEW.event_id, OLD.event_id);
BEGIN
  UPDATE events e
     SET going_count = (
       SELECT COUNT(*) FROM attendees a
        WHERE a.event_id = target AND a.status = 'approved'
     )
   WHERE e.id = target;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS attendees_sync_going_count ON attendees;
CREATE TRIGGER attendees_sync_going_count
  AFTER INSERT OR UPDATE OR DELETE ON attendees
  FOR EACH ROW EXECUTE FUNCTION sync_event_going_count();

-- ============================================================================
-- 0004_storage.sql
-- ============================================================================

-- Cover-image bucket for the event form's upload field.
-- Public read, authenticated write, and every object lives under a folder named
-- for its uploader — so nobody can overwrite, or list into, someone else's files.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'event-images',
  'event-images',
  true,
  5242880, -- 5 MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
ON CONFLICT (id) DO UPDATE
  SET public             = EXCLUDED.public,
      file_size_limit    = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "event images are publicly readable" ON storage.objects;
CREATE POLICY "event images are publicly readable"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'event-images');

-- Path convention: event-images/<auth.uid()>/<uuid>.<ext>
DROP POLICY IF EXISTS "authenticated users upload to their own folder" ON storage.objects;
CREATE POLICY "authenticated users upload to their own folder"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'event-images'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "users update their own event images" ON storage.objects;
CREATE POLICY "users update their own event images"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'event-images'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "users delete their own event images" ON storage.objects;
CREATE POLICY "users delete their own event images"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'event-images'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
