#!/usr/bin/env bash
# Regenerates supabase/setup-all.sql — every migration concatenated in order, for
# people setting the database up by pasting into the Supabase dashboard's SQL
# Editor rather than running the CLI.
#
# Run this after adding or changing anything in supabase/migrations/.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/setup-all.sql"

{
  cat <<'HEADER'
-- ============================================================================
-- Overlap — complete database setup, in one file.
--
-- This is every file in supabase/migrations/ concatenated in order, for people
-- setting up through the Supabase dashboard instead of the CLI:
--
--   Supabase project -> SQL Editor -> New query -> paste all of this -> Run
--
-- Safe to re-run: every statement is written to be idempotent (IF NOT EXISTS,
-- DROP POLICY IF EXISTS, ON CONFLICT DO UPDATE).
--
-- If you're using the Supabase CLI instead, ignore this file and run
-- `supabase db push` — it applies supabase/migrations/* and tracks which have
-- already run. Don't do both; they create the same objects.
--
-- Generated by scripts/build-setup-sql.sh — edit the migrations, not this file.
-- ============================================================================

HEADER

  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo ""
    echo "-- ============================================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================================"
    echo ""
    cat "$f"
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
